### PR TITLE
update for 3.2

### PR DESCRIPTION
**Pull request by blueblank**
Just reading the thread for issue #7:

iquest seems to have updated this, but I haven't tried / tested, yet.

It is just easier to fork and send pull request from here than wait for iquest to respond and contact you.

### CODE REVIEW

**Comment by jlsync** [comment]
works for me.

**Comment by troessner** [comment]
@stephencelis would be great if you could merge this....

**Comment by stephencelis** [comment]
Merged, thanks!

**Comment by troessner** [comment]
Thanks likewise!....:-)

**Pull request closed without merging**
